# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_--_PSGHDmXAM6VqI29M6G1AWvLvton
"""

import pandas as pd
import sqlite3
import string

"""Extract fetches grant application data from source CSV"""

def extract(filepath):
    df = pd.read_csv(filepath, encoding='latin-1')
    return df

Grants_1 = extract("grants_samplesource.csv")

"""Transform cleans column names, handles null values, parses grant dollar amounts/dates, and standardizes formats"""

def transform(df):
    df[' Amount '] = df[' Amount '].str.replace('$', '', regex=False).str.replace(',', '', regex=False).str.strip()
    df[' Amount '] = pd.to_numeric(df[' Amount '], errors='coerce')
    df[' Amount '] = df[' Amount '] * 1.3
    df[' Total Project Cost '] = df[' Total Project Cost '].str.replace('$', '', regex=False).str.replace(',', '', regex=False).str.strip()
    df[' Total Project Cost '] = pd.to_numeric(df[' Total Project Cost '], errors='coerce')
    df[' Total Project Cost '] = df[' Total Project Cost '] * 1.3
    df = df.drop(columns=['Local Contact', 'TIP Status'])
    df['Project Title'] = labels[:len(df)]
    return df

labels = []
for x in string.ascii_uppercase:
    labels.append(x)
    for y in string.ascii_uppercase:
        labels.append(x + y)
        if len(labels) == 119:
            break
    if len(labels) == 119:
        break

print(len(labels))

Grants_1 = extract("grants_samplesource.csv")
Grants_1 = transform(Grants_1)
print(Grants_1[' Amount '].head(5))
print(Grants_1['Project Title'].head(5))

"""Load adds cleaned DataFrame into the target database grants.db"""

def load(df):
    conn = sqlite3.connect('grants.db')
    df.to_sql('grants', conn, if_exists='replace')

"""Main combines ETL functions to run full pipeline"""

def main():
    df = extract("grants_samplesource.csv")
    df = transform(df)
    load(df)

main()

conn2 = sqlite3.connect('grants.db')
print(pd.read_sql('SELECT * FROM grants LIMIT 5', conn2))

print(pd.read_sql("SELECT \" Amount \", \" Total Project Cost \" FROM grants LIMIT 5", conn2))

conn3 = sqlite3.connect('grants.db')
print(pd.read_sql('SELECT * FROM grants LIMIT 3', conn3))
